name: Benchmark

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

jobs:
  benchmark_linux:
    if: github.event_name == 'pull_request'
    # if: ${{ github.event.label.name == 'run-benchmark' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Linux
    runs-on: ubuntu-20.04

    steps:
      # We need the full repo to avoid this issue
      # https://github.com/actions/checkout/issues/23
      - uses: actions/checkout@v2
        with:
          # ref: ${{github.event.pull_request.head.ref}}
          # repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2

      - name: Setup some dependencies
        shell: bash -l {0}
        run:
          pip install asv

      - name: Run benchmarks
        shell: bash -l {0}
        id: benchmark
        env:
          OPENBLAS_NUM_THREADS: 1
          MKL_NUM_THREADS: 1
          OMP_NUM_THREADS: 1
          ASV_FACTOR: 1.4
        run: |
          set -x

          # ID this runner
          asv machine --yes

          echo "Baseline:  ${{ github.event.pull_request.base.sha }} (${{ github.event.pull_request.base.label }})"
          echo "Contender: ${GITHUB_SHA} (${{ github.event.pull_request.head.label }})"

          # Run benchmarks for current commit against base
          # See https://github.com/airspeed-velocity/asv/issues/595 for discussion on interleaved processes
          ASV_OPTIONS="--split --show-stderr --interleave-processes --factor $ASV_FACTOR"
          asv continuous $ASV_OPTIONS ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA} \
              | sed "/Traceback \|failed$\|PERFORMANCE DECREASED/ s/^/::error::/" \
              | tee benchmarks.log

          # Report and export results for subsequent steps
          if grep "Traceback \|failed\|PERFORMANCE DECREASED" benchmarks.log > /dev/null ; then
              exit 1
          fi

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: asv-benchmark-results
          path: .asv/results

  benchmark_report:
    if: github.event_name == 'pull_request_target'
    # if: ${{ github.event.label.name == 'run-benchmark' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Report benchmark
    runs-on: ubuntu-20.04
    steps:
      - name: Write message
        id: message
        run: |
          echo "::set-output name=content::Benchmarks are running! Check [logs here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})."

      - name: Post link to logs
        if: always()
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ steps.message.outputs.content }}`
            })